In [1]:
from torchvision import datasets, transforms
import sklearn
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader
import torch.nn.functional as F

In [26]:
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
%matplotlib inline
import time
import torch
import torch.nn as nn

In [3]:
transform = transforms.ToTensor()
train_dataset = datasets.MNIST(
    root="../Datasets", train=True, download=False, transform=transform)
train_dataset

/Users/abhimanyubellam/Library/Python/3.7/lib/python/site-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


Dataset MNIST
    Number of datapoints: 60000
    Root location: ../Datasets
    Split: Train
    StandardTransform
Transform: ToTensor()

In [5]:
test_dataset = datasets.MNIST(
    root="../Datasets", train=False, download=False, transform=transform)
test_dataset

Dataset MNIST
    Number of datapoints: 10000
    Root location: ../Datasets
    Split: Test
    StandardTransform
Transform: ToTensor()

In [6]:
train_loader = DataLoader(train_dataset, batch_size=1, shuffle=False)
test_loadder = DataLoader(test_dataset, batch_size=1, shuffle=False)

In [4]:
from base_net import BasicNet


In [5]:
basic_net1 = BasicNet()
cost_func = nn.CrossEntropyLoss()

In [9]:
for images, labels in train_loader:
    print ("init bacth shape", images.size())
    break
images.view(1,-1).size()

init bacth shape torch.Size([1, 1, 28, 28])


torch.Size([1, 784])

In [26]:
# configs
batch_size = 1


from tqdm import tqdm

In [25]:
def train(generations, model):
    best_candidate_losses = []
    for i in tqdm(range(generations)):
        gen_train_loss=[]
        gen_train_acc=0
        for b, (X_train, y_train) in enumerate(train_loader):
            b+=1
            # run model, get loss
            y_pred = model(X_train.view(batch_size, -1)) # flatten and evaluate
            loss = cost_func(y_pred, y_train)
            gen_train_loss.append(loss)
            
            
            predicted = torch.max(y_pred.data, 1)[1]
            
            gen_train_acc+= (predicted==y_test).sum()
            
            
            
            # visualize for best candidate
        gen_train_loss_total = sum(gen_train_loss)
        print (f"Gen:{i}, loss: {gen_train_loss_total}, acc: {gen_train_acc}")
        
        #evolve
            

In [27]:
basic_net1.d3.weight

Parameter containing:
tensor([[-0.1593,  0.0225,  0.2888,  0.3428],
        [-0.3278, -0.0073,  0.2181,  0.4480],
        [-0.0464, -0.2075, -0.2040, -0.3577],
        [-0.0382,  0.1869,  0.0812,  0.3034],
        [-0.0933,  0.2894, -0.1449, -0.4228],
        [ 0.2317, -0.3001, -0.2485,  0.1962],
        [ 0.2957,  0.0304, -0.0007,  0.4728],
        [-0.4343,  0.2107,  0.3733, -0.3766],
        [-0.3006,  0.4164,  0.0547,  0.2784],
        [-0.4473,  0.0134,  0.0057, -0.1768]], requires_grad=True)

In [7]:
basic_net2 = BasicNet()
basic_net2.d3.weight

Parameter containing:
tensor([[ 0.2848,  0.2090,  0.4117, -0.3648],
        [-0.0597, -0.1142,  0.4644, -0.1160],
        [-0.2047, -0.4819,  0.3412,  0.2054],
        [ 0.0358, -0.0541, -0.4511, -0.3880],
        [-0.4673, -0.1311, -0.0020,  0.1218],
        [ 0.1130, -0.4485, -0.2412,  0.2773],
        [-0.4218, -0.2839,  0.3953,  0.1766],
        [-0.3097,  0.3797,  0.3349,  0.1339],
        [-0.3377,  0.1392, -0.3575, -0.2464],
        [-0.1845,  0.3202,  0.1019,  0.1065]], requires_grad=True)

In [21]:
basic_net2.d3.weight.flatten().shape[0]

40

In [25]:
basic_net2.d3.bias.shape

torch.Size([10])

In [16]:
arr = np.zeros((4,10))
arr = torch.tensor(arr)
with torch.no_grad():
    basic_net2.d2.weight.data=arr
basic_net2.d2.weight

Parameter containing:
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=torch.float64,
       requires_grad=True)

In [22]:
basic_net2.d3.weight.shape

torch.Size([10, 4])